### PR TITLE
Update build_and_test.yml

### PR DESCRIPTION
**Pull request by Lee245**
Update Java version tot 17

### CODE REVIEW

**Review by CNugteren — APPROVED** [review]

**Comment by CNugteren** [comment]
Thanks for the update. There are still some issues with the build job though it seems:
https://github.com/CNugteren/NLWeer/actions/runs/8015876496/job/21896781326

**Comment by Lee245** [comment]
> Thanks for the update. There are still some issues with the build job though it seems: https://github.com/CNugteren/NLWeer/actions/runs/8015876496/job/21896781326 I can also have a look at it later.

Yeah, saw it. It's complaining about the target SDK not being 34. In the 6-day forecast PR I updated the SDK to 34, so once that's in it should work

**Comment by CNugteren** [comment]
Great, thanks. Just to be sure, does this `Requirement is an Android device with version 5.0 (Lollipop, API 21) or newer` from the README still hold if we update to 34?

**Comment by Lee245** [comment]
You're welcome! As far as I understand, the Android SDK's are backwards compatible. The only thing you need to watch out for is that you do not use any classes/methods/.. introduced in an SDK later than 21 which, as far as I can see, I did not do so far.

**Pull request merged**
